### PR TITLE
added initial files

### PR DESCRIPTION
**Pull request by justinal64**

### CODE REVIEW

**Comment by justinal64** [comment]
@ncgonz I have completed the assignment. Let me know what you think.

**Comment by JoeShep** [comment]
Justin, this works well and shows a nice grasp of JS, even beyond the basics we've covered so far. Impressive. I do need to point out one thing: The requirements state that your function for growing the tree "accepts a single object as an argument. The object should have two key/value pairs." So, tweak this to create an object using the size and character vars as properties, and pass that into `createTree`. Just want to make sure all the requirements are met. On the job product owners can get finicky if the devs aren't following the spec.

Take care of that and you're good to go!

**Comment by justinal64** [comment]
@JoeShep Would you like to review this again before I commit it? I believe I made the changes you asked for.  
var calculate = {size: size, character: character};
function createTree(calculate) {}

**Comment by JoeShep** [comment]
👍 Merge it!

**Pull request merged**
